{
    'name': 'TikTok Shop Connector',
    'summary': 'Mirror TikTok Shop data into Odoo (Phase 1 - read-only sync)',
    'version': '1.0.8',
    'category': 'Connector',
    'author': 'Fani',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        "security/ir.model.access.csv",
        "data/cron_data.xml",
        "views/tiktok_shop_views.xml",
        "views/tiktok_category_views.xml",
        "views/tiktok_warehouse_views.xml",
        "views/tiktok_product_views.xml",
        "views/tiktok_sku_views.xml",
        "views/tiktok_sku_inventory_views.xml",
        "views/tiktok_order_views.xml",
        "views/tiktok_order_line_views.xml",
        "views/tiktok_return_views.xml",
        "views/tiktok_return_line_views.xml",
        "views/tiktok_return_reason_views.xml",
        "views/tiktok_cancel_views.xml",
        "views/tiktok_cancel_line_views.xml",
        "views/tiktok_cancel_reason_views.xml",
        "views/tiktok_product_performance_views.xml",
        "views/tiktok_sku_performance_views.xml",
        "views/tiktok_video_performance_views.xml",
        "views/tiktok_live_performance_views.xml",
        "views/tiktok_menus.xml",
    ],
    'demo': [],
    'application': True,
    'installable': True,
}
