{
    'name': 'Shopee Report Importer',
    'summary': 'Mirror Shopee Report data into Odoo (Phase 1 - import from file)',
    'version': '1.0.0',
    'category': 'Connector',
    'author': 'Fani',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'data/cron_data.xml',
        'views/shopee_shop_views.xml',
        'views/ads_cpc_report_views.xml',
        'views/ads_live_report_views.xml',
        'views/booking_report_views.xml',
        'views/laban_report_views.xml',
        'views/live_product_report_views.xml',
        'views/order_report_views.xml',
        'views/video_product_report_views.xml',
        'views/shopee_menu.xml',
    ],
    'demo': [],
    'application': True,
    'installable': True,
}
