# -*- coding: utf-8 -*-
{
    'name': 'Odoo - JST',
    'version': '0.1.4',
    'category': 'Sales',
    'summary': 'Odoo - JST',
    'description': """Odoo - JST
    """,
    'author': 'Nguyen Viet Phuong',
    'depends': ['base_setup'],
    'data': [
        'security/ir.model.access.csv',
        'data/cron_sync.xml',
        'views/jst_shop_view.xml',
        'views/jst_shop_product.xml',
        'views/jst_product_template_views.xml',
        'views/jst_product_product_views.xml',
        'views/jst_sale_order.xml',
        'views/jst_sale_order_line.xml',
        'views/jst_sale_order_after.xml',
        'views/jst_sale_order_line_after.xml',
        'views/jst_warehouse.xml',
        'views/jst_product_inventory.xml',
        'views/jst_warehouse_inventory.xml',
        'views/jst_logistic_company_view.xml',
        'views/jst_stock_inout.xml',
        'views/jst_stock_inout_item.xml',
        'views/jst_stock_tranfer.xml',
        'views/jst_purchase_order.xml',
        'views/jst_user_view.xml',
        'views/jst_wave_shipping_views.xml',
        'views/res_config_settings.xml',
        'views/menu.xml',
        'wizards/views/wizard_sync_jst_shop.xml',
        'wizards/views/wizard_sync_jst_product_template.xml',
        'wizards/views/wizard_sync_jst_product_product.xml',
        'wizards/views/wizard_sync_jst_order.xml',
        'wizards/views/wizard_sync_jst_order_after.xml',
        'wizards/views/wizard_sync_jst_product_inventory.xml',
        'wizards/views/wizard_sync_jst_warehouse_inventory.xml',
        'wizards/views/wizard_sync_jst_logistic_company.xml',
        'wizards/views/wizard_sync_jst_stock_inpout.xml',
        'wizards/views/wizard_sync_jst_purchase_order.xml',
        'wizards/views/wizard_sync_jst_user.xml',
        'wizards/views/wizard_sync_jst_wave_shipping.xml',
        'wizards/views/wizard_sync_jst_tranfer.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
